export default {
	AppCategories: [
		"Framework",
		"Forms",
		"Queries/APIs",
		"Widgets",
		"JS Promises/Async Await",
		"Utility",
		"Date-Time",
		"UI Components",
		"Pagination",
		"Table",
		"Navigation",
		"Charts",
		"Bulk insert/update",
		"None"
	],
	AppTags: [
		"Framework",
		"Forms",
		"Queries/APIs",
		"Widgets",
		"JS Promises/Async Await",
		"Utility",
		"Date-Time",
		"UI Components",
		"Pagination",
		"Table",
		"Navigation",
		"Charts",
		"Bulk insert/update",
		"Store",
		"Modal Widget",
		"Text Widget",
		"Select Widget",
	],
	States: [
		"Requested",
		"Needs Revamp",
		"Built",
		"Published",
		"None"
	],
}